### ISSUE TITLE
Cap_getPropertyLimits doesn't work on macOS

### ISSUE THREAD

**Issue by ronaaron** [openpnp/openpnp-capture#38] opened 2020-08-09 05:34 UTC
Running macOS 10.5, I get CAPRESULT_PROPERTYNOTSUPPORTED for all properties.
I can capture frames just fine, though.

This is with a RELEASE build, STATIC library.

**Comment by ronaaron** [comment] 2020-08-10 03:46
Turned logging all the way up, and got this:
````
[DBG ] Setup for capture format (1280 x 720)...
[DBG ] UVCCtrl::findDevice() called
[DBG ] UVCCtrl::findDevice() Camera control error -536870210
[DBG ] Could not create a UVC control object! -- settings will not be available!
````

**Comment by ronaaron** [comment] 2020-08-10 03:53
Apparently the root cause is `OSX Unique ID is not exactly 18 characters - wrong format to extract location`.

Is there a workaround for this? It's funny, because there's only the one camera on this MBP... it shouldn't be difficult to identify.

**Comment by ronaaron** [comment] 2020-08-10 10:35
I just noticed this is talked about in another issue... but I'll leave it open for now in case someone has an idea.

**Comment by trcwm** [comment] 2020-08-27 12:40
Some cameras don't have any or very few settable properties. They will return a PROPERTYNOTSUPPORTED error.
However, it looks like you are running into a OSX permission issue. I think this has been fixed in the latest master branch. Can you confirm this? I don't have OSX to test this myself.

**Comment by vonnieda** [comment] 2022-03-17 21:41
Closing stale issue. Please reopen if the issue is still relevant with the latest version.

**Closed by vonnieda** 2022-03-17 21:41 UTC
